// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: libravdb/ipc/v1/rpc.proto

package ipcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LibravDB_Health_FullMethodName                  = "/libravdb.ipc.v1.LibravDB/Health"
	LibravDB_Status_FullMethodName                  = "/libravdb.ipc.v1.LibravDB/Status"
	LibravDB_DaemonStatus_FullMethodName            = "/libravdb.ipc.v1.LibravDB/DaemonStatus"
	LibravDB_EvictTenant_FullMethodName             = "/libravdb.ipc.v1.LibravDB/EvictTenant"
	LibravDB_Flush_FullMethodName                   = "/libravdb.ipc.v1.LibravDB/Flush"
	LibravDB_SessionLifecycleHint_FullMethodName    = "/libravdb.ipc.v1.LibravDB/SessionLifecycleHint"
	LibravDB_ListLifecycleJournal_FullMethodName    = "/libravdb.ipc.v1.LibravDB/ListLifecycleJournal"
	LibravDB_EnsureCollections_FullMethodName       = "/libravdb.ipc.v1.LibravDB/EnsureCollections"
	LibravDB_IngestMarkdownDocument_FullMethodName  = "/libravdb.ipc.v1.LibravDB/IngestMarkdownDocument"
	LibravDB_PromoteDreamEntries_FullMethodName     = "/libravdb.ipc.v1.LibravDB/PromoteDreamEntries"
	LibravDB_ReindexAuthoredDocument_FullMethodName = "/libravdb.ipc.v1.LibravDB/ReindexAuthoredDocument"
	LibravDB_DeleteAuthoredDocument_FullMethodName  = "/libravdb.ipc.v1.LibravDB/DeleteAuthoredDocument"
	LibravDB_MarkMemorySuperseded_FullMethodName    = "/libravdb.ipc.v1.LibravDB/MarkMemorySuperseded"
	LibravDB_InsertText_FullMethodName              = "/libravdb.ipc.v1.LibravDB/InsertText"
	LibravDB_InsertSessionTurn_FullMethodName       = "/libravdb.ipc.v1.LibravDB/InsertSessionTurn"
	LibravDB_GatingScalar_FullMethodName            = "/libravdb.ipc.v1.LibravDB/GatingScalar"
	LibravDB_SearchText_FullMethodName              = "/libravdb.ipc.v1.LibravDB/SearchText"
	LibravDB_SearchTextCollections_FullMethodName   = "/libravdb.ipc.v1.LibravDB/SearchTextCollections"
	LibravDB_BumpAccessCounts_FullMethodName        = "/libravdb.ipc.v1.LibravDB/BumpAccessCounts"
	LibravDB_ListCollection_FullMethodName          = "/libravdb.ipc.v1.LibravDB/ListCollection"
	LibravDB_ListByMeta_FullMethodName              = "/libravdb.ipc.v1.LibravDB/ListByMeta"
	LibravDB_ExportMemory_FullMethodName            = "/libravdb.ipc.v1.LibravDB/ExportMemory"
	LibravDB_FlushNamespace_FullMethodName          = "/libravdb.ipc.v1.LibravDB/FlushNamespace"
	LibravDB_Delete_FullMethodName                  = "/libravdb.ipc.v1.LibravDB/Delete"
	LibravDB_DeleteBatch_FullMethodName             = "/libravdb.ipc.v1.LibravDB/DeleteBatch"
	LibravDB_CompactSession_FullMethodName          = "/libravdb.ipc.v1.LibravDB/CompactSession"
	LibravDB_SummarizeMessages_FullMethodName       = "/libravdb.ipc.v1.LibravDB/SummarizeMessages"
	LibravDB_ExpandSummary_FullMethodName           = "/libravdb.ipc.v1.LibravDB/ExpandSummary"
	LibravDB_QueryRawSession_FullMethodName         = "/libravdb.ipc.v1.LibravDB/QueryRawSession"
	LibravDB_RebuildIndex_FullMethodName            = "/libravdb.ipc.v1.LibravDB/RebuildIndex"
	LibravDB_BootstrapSessionKernel_FullMethodName  = "/libravdb.ipc.v1.LibravDB/BootstrapSessionKernel"
	LibravDB_IngestMessageKernel_FullMethodName     = "/libravdb.ipc.v1.LibravDB/IngestMessageKernel"
	LibravDB_BeforeTurnKernel_FullMethodName        = "/libravdb.ipc.v1.LibravDB/BeforeTurnKernel"
	LibravDB_AfterTurnKernel_FullMethodName         = "/libravdb.ipc.v1.LibravDB/AfterTurnKernel"
	LibravDB_AssembleContextInternal_FullMethodName = "/libravdb.ipc.v1.LibravDB/AssembleContextInternal"
	LibravDB_RankCandidates_FullMethodName          = "/libravdb.ipc.v1.LibravDB/RankCandidates"
	LibravDB_CognitiveMetrics_FullMethodName        = "/libravdb.ipc.v1.LibravDB/CognitiveMetrics"
)

// LibravDBClient is the client API for LibravDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LibravDBClient interface {
	// Session lifecycle
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Status(ctx context.Context, in *MemoryStatusRequest, opts ...grpc.CallOption) (*MemoryStatusResponse, error)
	DaemonStatus(ctx context.Context, in *DaemonStatusRequest, opts ...grpc.CallOption) (*DaemonStatusResponse, error)
	EvictTenant(ctx context.Context, in *EvictTenantRequest, opts ...grpc.CallOption) (*EvictTenantResponse, error)
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	SessionLifecycleHint(ctx context.Context, in *SessionLifecycleHintRequest, opts ...grpc.CallOption) (*SessionLifecycleHintResponse, error)
	ListLifecycleJournal(ctx context.Context, in *ListLifecycleJournalRequest, opts ...grpc.CallOption) (*ListLifecycleJournalResponse, error)
	// Collections
	EnsureCollections(ctx context.Context, in *EnsureCollectionsRequest, opts ...grpc.CallOption) (*EnsureCollectionsResponse, error)
	// Ingest
	IngestMarkdownDocument(ctx context.Context, in *IngestMarkdownDocumentRequest, opts ...grpc.CallOption) (*IngestMarkdownDocumentResponse, error)
	PromoteDreamEntries(ctx context.Context, in *PromoteDreamEntriesRequest, opts ...grpc.CallOption) (*DreamPromotionResponse, error)
	ReindexAuthoredDocument(ctx context.Context, in *ReindexAuthoredDocumentRequest, opts ...grpc.CallOption) (*ReindexAuthoredDocumentResponse, error)
	DeleteAuthoredDocument(ctx context.Context, in *DeleteAuthoredDocumentRequest, opts ...grpc.CallOption) (*DeleteAuthoredDocumentResponse, error)
	MarkMemorySuperseded(ctx context.Context, in *MarkMemorySupersededRequest, opts ...grpc.CallOption) (*MarkMemorySupersededResponse, error)
	// Insert
	InsertText(ctx context.Context, in *InsertTextRequest, opts ...grpc.CallOption) (*InsertTextResponse, error)
	InsertSessionTurn(ctx context.Context, in *InsertSessionTurnRequest, opts ...grpc.CallOption) (*InsertSessionTurnResponse, error)
	// Ranking and gating
	GatingScalar(ctx context.Context, in *GatingScalarRequest, opts ...grpc.CallOption) (*GatingScalarResponse, error)
	SearchText(ctx context.Context, in *SearchTextRequest, opts ...grpc.CallOption) (*SearchTextResponse, error)
	SearchTextCollections(ctx context.Context, in *SearchTextCollectionsRequest, opts ...grpc.CallOption) (*SearchTextResponse, error)
	BumpAccessCounts(ctx context.Context, in *BumpAccessCountsRequest, opts ...grpc.CallOption) (*BumpAccessCountsResponse, error)
	// Query
	ListCollection(ctx context.Context, in *ListCollectionRequest, opts ...grpc.CallOption) (*ListCollectionResponse, error)
	ListByMeta(ctx context.Context, in *ListByMetaRequest, opts ...grpc.CallOption) (*ListByMetaResponse, error)
	// Memory
	ExportMemory(ctx context.Context, in *ExportMemoryRequest, opts ...grpc.CallOption) (*ExportMemoryResponse, error)
	FlushNamespace(ctx context.Context, in *FlushNamespaceRequest, opts ...grpc.CallOption) (*FlushNamespaceResponse, error)
	// Delete
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteBatch(ctx context.Context, in *DeleteBatchRequest, opts ...grpc.CallOption) (*DeleteBatchResponse, error)
	// Session
	CompactSession(ctx context.Context, in *CompactSessionRequest, opts ...grpc.CallOption) (*CompactSessionResponse, error)
	SummarizeMessages(ctx context.Context, in *SummarizeMessagesRequest, opts ...grpc.CallOption) (*SummarizeMessagesResponse, error)
	ExpandSummary(ctx context.Context, in *ExpandSummaryRequest, opts ...grpc.CallOption) (*ExpandSummaryResponse, error)
	QueryRawSession(ctx context.Context, in *QueryRawSessionRequest, opts ...grpc.CallOption) (*QueryRawSessionResponse, error)
	// Index
	RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...grpc.CallOption) (*RebuildIndexResponse, error)
	// Kernel
	BootstrapSessionKernel(ctx context.Context, in *BootstrapSessionKernelRequest, opts ...grpc.CallOption) (*BootstrapSessionKernelResponse, error)
	IngestMessageKernel(ctx context.Context, in *IngestMessageKernelRequest, opts ...grpc.CallOption) (*IngestMessageKernelResponse, error)
	BeforeTurnKernel(ctx context.Context, in *BeforeTurnKernelRequest, opts ...grpc.CallOption) (*BeforeTurnKernelResponse, error)
	AfterTurnKernel(ctx context.Context, in *AfterTurnKernelRequest, opts ...grpc.CallOption) (*AfterTurnKernelResponse, error)
	AssembleContextInternal(ctx context.Context, in *AssembleContextInternalRequest, opts ...grpc.CallOption) (*AssembleContextInternalResponse, error)
	// Ranking
	RankCandidates(ctx context.Context, in *RankCandidatesRequest, opts ...grpc.CallOption) (*RankCandidatesResponse, error)
	// Cognitive
	CognitiveMetrics(ctx context.Context, in *CognitiveMetricsRequest, opts ...grpc.CallOption) (*CognitiveMetricsResponse, error)
}

type libravDBClient struct {
	cc grpc.ClientConnInterface
}

func NewLibravDBClient(cc grpc.ClientConnInterface) LibravDBClient {
	return &libravDBClient{cc}
}

func (c *libravDBClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LibravDB_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) Status(ctx context.Context, in *MemoryStatusRequest, opts ...grpc.CallOption) (*MemoryStatusResponse, error) {
	out := new(MemoryStatusResponse)
	err := c.cc.Invoke(ctx, LibravDB_Status_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) DaemonStatus(ctx context.Context, in *DaemonStatusRequest, opts ...grpc.CallOption) (*DaemonStatusResponse, error) {
	out := new(DaemonStatusResponse)
	err := c.cc.Invoke(ctx, LibravDB_DaemonStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) EvictTenant(ctx context.Context, in *EvictTenantRequest, opts ...grpc.CallOption) (*EvictTenantResponse, error) {
	out := new(EvictTenantResponse)
	err := c.cc.Invoke(ctx, LibravDB_EvictTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, LibravDB_Flush_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) SessionLifecycleHint(ctx context.Context, in *SessionLifecycleHintRequest, opts ...grpc.CallOption) (*SessionLifecycleHintResponse, error) {
	out := new(SessionLifecycleHintResponse)
	err := c.cc.Invoke(ctx, LibravDB_SessionLifecycleHint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) ListLifecycleJournal(ctx context.Context, in *ListLifecycleJournalRequest, opts ...grpc.CallOption) (*ListLifecycleJournalResponse, error) {
	out := new(ListLifecycleJournalResponse)
	err := c.cc.Invoke(ctx, LibravDB_ListLifecycleJournal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) EnsureCollections(ctx context.Context, in *EnsureCollectionsRequest, opts ...grpc.CallOption) (*EnsureCollectionsResponse, error) {
	out := new(EnsureCollectionsResponse)
	err := c.cc.Invoke(ctx, LibravDB_EnsureCollections_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) IngestMarkdownDocument(ctx context.Context, in *IngestMarkdownDocumentRequest, opts ...grpc.CallOption) (*IngestMarkdownDocumentResponse, error) {
	out := new(IngestMarkdownDocumentResponse)
	err := c.cc.Invoke(ctx, LibravDB_IngestMarkdownDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) PromoteDreamEntries(ctx context.Context, in *PromoteDreamEntriesRequest, opts ...grpc.CallOption) (*DreamPromotionResponse, error) {
	out := new(DreamPromotionResponse)
	err := c.cc.Invoke(ctx, LibravDB_PromoteDreamEntries_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) ReindexAuthoredDocument(ctx context.Context, in *ReindexAuthoredDocumentRequest, opts ...grpc.CallOption) (*ReindexAuthoredDocumentResponse, error) {
	out := new(ReindexAuthoredDocumentResponse)
	err := c.cc.Invoke(ctx, LibravDB_ReindexAuthoredDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) DeleteAuthoredDocument(ctx context.Context, in *DeleteAuthoredDocumentRequest, opts ...grpc.CallOption) (*DeleteAuthoredDocumentResponse, error) {
	out := new(DeleteAuthoredDocumentResponse)
	err := c.cc.Invoke(ctx, LibravDB_DeleteAuthoredDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) MarkMemorySuperseded(ctx context.Context, in *MarkMemorySupersededRequest, opts ...grpc.CallOption) (*MarkMemorySupersededResponse, error) {
	out := new(MarkMemorySupersededResponse)
	err := c.cc.Invoke(ctx, LibravDB_MarkMemorySuperseded_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) InsertText(ctx context.Context, in *InsertTextRequest, opts ...grpc.CallOption) (*InsertTextResponse, error) {
	out := new(InsertTextResponse)
	err := c.cc.Invoke(ctx, LibravDB_InsertText_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) InsertSessionTurn(ctx context.Context, in *InsertSessionTurnRequest, opts ...grpc.CallOption) (*InsertSessionTurnResponse, error) {
	out := new(InsertSessionTurnResponse)
	err := c.cc.Invoke(ctx, LibravDB_InsertSessionTurn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) GatingScalar(ctx context.Context, in *GatingScalarRequest, opts ...grpc.CallOption) (*GatingScalarResponse, error) {
	out := new(GatingScalarResponse)
	err := c.cc.Invoke(ctx, LibravDB_GatingScalar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) SearchText(ctx context.Context, in *SearchTextRequest, opts ...grpc.CallOption) (*SearchTextResponse, error) {
	out := new(SearchTextResponse)
	err := c.cc.Invoke(ctx, LibravDB_SearchText_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) SearchTextCollections(ctx context.Context, in *SearchTextCollectionsRequest, opts ...grpc.CallOption) (*SearchTextResponse, error) {
	out := new(SearchTextResponse)
	err := c.cc.Invoke(ctx, LibravDB_SearchTextCollections_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) BumpAccessCounts(ctx context.Context, in *BumpAccessCountsRequest, opts ...grpc.CallOption) (*BumpAccessCountsResponse, error) {
	out := new(BumpAccessCountsResponse)
	err := c.cc.Invoke(ctx, LibravDB_BumpAccessCounts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) ListCollection(ctx context.Context, in *ListCollectionRequest, opts ...grpc.CallOption) (*ListCollectionResponse, error) {
	out := new(ListCollectionResponse)
	err := c.cc.Invoke(ctx, LibravDB_ListCollection_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) ListByMeta(ctx context.Context, in *ListByMetaRequest, opts ...grpc.CallOption) (*ListByMetaResponse, error) {
	out := new(ListByMetaResponse)
	err := c.cc.Invoke(ctx, LibravDB_ListByMeta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) ExportMemory(ctx context.Context, in *ExportMemoryRequest, opts ...grpc.CallOption) (*ExportMemoryResponse, error) {
	out := new(ExportMemoryResponse)
	err := c.cc.Invoke(ctx, LibravDB_ExportMemory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) FlushNamespace(ctx context.Context, in *FlushNamespaceRequest, opts ...grpc.CallOption) (*FlushNamespaceResponse, error) {
	out := new(FlushNamespaceResponse)
	err := c.cc.Invoke(ctx, LibravDB_FlushNamespace_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, LibravDB_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) DeleteBatch(ctx context.Context, in *DeleteBatchRequest, opts ...grpc.CallOption) (*DeleteBatchResponse, error) {
	out := new(DeleteBatchResponse)
	err := c.cc.Invoke(ctx, LibravDB_DeleteBatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) CompactSession(ctx context.Context, in *CompactSessionRequest, opts ...grpc.CallOption) (*CompactSessionResponse, error) {
	out := new(CompactSessionResponse)
	err := c.cc.Invoke(ctx, LibravDB_CompactSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) SummarizeMessages(ctx context.Context, in *SummarizeMessagesRequest, opts ...grpc.CallOption) (*SummarizeMessagesResponse, error) {
	out := new(SummarizeMessagesResponse)
	err := c.cc.Invoke(ctx, LibravDB_SummarizeMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) ExpandSummary(ctx context.Context, in *ExpandSummaryRequest, opts ...grpc.CallOption) (*ExpandSummaryResponse, error) {
	out := new(ExpandSummaryResponse)
	err := c.cc.Invoke(ctx, LibravDB_ExpandSummary_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) QueryRawSession(ctx context.Context, in *QueryRawSessionRequest, opts ...grpc.CallOption) (*QueryRawSessionResponse, error) {
	out := new(QueryRawSessionResponse)
	err := c.cc.Invoke(ctx, LibravDB_QueryRawSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...grpc.CallOption) (*RebuildIndexResponse, error) {
	out := new(RebuildIndexResponse)
	err := c.cc.Invoke(ctx, LibravDB_RebuildIndex_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) BootstrapSessionKernel(ctx context.Context, in *BootstrapSessionKernelRequest, opts ...grpc.CallOption) (*BootstrapSessionKernelResponse, error) {
	out := new(BootstrapSessionKernelResponse)
	err := c.cc.Invoke(ctx, LibravDB_BootstrapSessionKernel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) IngestMessageKernel(ctx context.Context, in *IngestMessageKernelRequest, opts ...grpc.CallOption) (*IngestMessageKernelResponse, error) {
	out := new(IngestMessageKernelResponse)
	err := c.cc.Invoke(ctx, LibravDB_IngestMessageKernel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) BeforeTurnKernel(ctx context.Context, in *BeforeTurnKernelRequest, opts ...grpc.CallOption) (*BeforeTurnKernelResponse, error) {
	out := new(BeforeTurnKernelResponse)
	err := c.cc.Invoke(ctx, LibravDB_BeforeTurnKernel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) AfterTurnKernel(ctx context.Context, in *AfterTurnKernelRequest, opts ...grpc.CallOption) (*AfterTurnKernelResponse, error) {
	out := new(AfterTurnKernelResponse)
	err := c.cc.Invoke(ctx, LibravDB_AfterTurnKernel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) AssembleContextInternal(ctx context.Context, in *AssembleContextInternalRequest, opts ...grpc.CallOption) (*AssembleContextInternalResponse, error) {
	out := new(AssembleContextInternalResponse)
	err := c.cc.Invoke(ctx, LibravDB_AssembleContextInternal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) RankCandidates(ctx context.Context, in *RankCandidatesRequest, opts ...grpc.CallOption) (*RankCandidatesResponse, error) {
	out := new(RankCandidatesResponse)
	err := c.cc.Invoke(ctx, LibravDB_RankCandidates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libravDBClient) CognitiveMetrics(ctx context.Context, in *CognitiveMetricsRequest, opts ...grpc.CallOption) (*CognitiveMetricsResponse, error) {
	out := new(CognitiveMetricsResponse)
	err := c.cc.Invoke(ctx, LibravDB_CognitiveMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibravDBServer is the server API for LibravDB service.
// All implementations must embed UnimplementedLibravDBServer
// for forward compatibility
type LibravDBServer interface {
	// Session lifecycle
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Status(context.Context, *MemoryStatusRequest) (*MemoryStatusResponse, error)
	DaemonStatus(context.Context, *DaemonStatusRequest) (*DaemonStatusResponse, error)
	EvictTenant(context.Context, *EvictTenantRequest) (*EvictTenantResponse, error)
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	SessionLifecycleHint(context.Context, *SessionLifecycleHintRequest) (*SessionLifecycleHintResponse, error)
	ListLifecycleJournal(context.Context, *ListLifecycleJournalRequest) (*ListLifecycleJournalResponse, error)
	// Collections
	EnsureCollections(context.Context, *EnsureCollectionsRequest) (*EnsureCollectionsResponse, error)
	// Ingest
	IngestMarkdownDocument(context.Context, *IngestMarkdownDocumentRequest) (*IngestMarkdownDocumentResponse, error)
	PromoteDreamEntries(context.Context, *PromoteDreamEntriesRequest) (*DreamPromotionResponse, error)
	ReindexAuthoredDocument(context.Context, *ReindexAuthoredDocumentRequest) (*ReindexAuthoredDocumentResponse, error)
	DeleteAuthoredDocument(context.Context, *DeleteAuthoredDocumentRequest) (*DeleteAuthoredDocumentResponse, error)
	MarkMemorySuperseded(context.Context, *MarkMemorySupersededRequest) (*MarkMemorySupersededResponse, error)
	// Insert
	InsertText(context.Context, *InsertTextRequest) (*InsertTextResponse, error)
	InsertSessionTurn(context.Context, *InsertSessionTurnRequest) (*InsertSessionTurnResponse, error)
	// Ranking and gating
	GatingScalar(context.Context, *GatingScalarRequest) (*GatingScalarResponse, error)
	SearchText(context.Context, *SearchTextRequest) (*SearchTextResponse, error)
	SearchTextCollections(context.Context, *SearchTextCollectionsRequest) (*SearchTextResponse, error)
	BumpAccessCounts(context.Context, *BumpAccessCountsRequest) (*BumpAccessCountsResponse, error)
	// Query
	ListCollection(context.Context, *ListCollectionRequest) (*ListCollectionResponse, error)
	ListByMeta(context.Context, *ListByMetaRequest) (*ListByMetaResponse, error)
	// Memory
	ExportMemory(context.Context, *ExportMemoryRequest) (*ExportMemoryResponse, error)
	FlushNamespace(context.Context, *FlushNamespaceRequest) (*FlushNamespaceResponse, error)
	// Delete
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	DeleteBatch(context.Context, *DeleteBatchRequest) (*DeleteBatchResponse, error)
	// Session
	CompactSession(context.Context, *CompactSessionRequest) (*CompactSessionResponse, error)
	SummarizeMessages(context.Context, *SummarizeMessagesRequest) (*SummarizeMessagesResponse, error)
	ExpandSummary(context.Context, *ExpandSummaryRequest) (*ExpandSummaryResponse, error)
	QueryRawSession(context.Context, *QueryRawSessionRequest) (*QueryRawSessionResponse, error)
	// Index
	RebuildIndex(context.Context, *RebuildIndexRequest) (*RebuildIndexResponse, error)
	// Kernel
	BootstrapSessionKernel(context.Context, *BootstrapSessionKernelRequest) (*BootstrapSessionKernelResponse, error)
	IngestMessageKernel(context.Context, *IngestMessageKernelRequest) (*IngestMessageKernelResponse, error)
	BeforeTurnKernel(context.Context, *BeforeTurnKernelRequest) (*BeforeTurnKernelResponse, error)
	AfterTurnKernel(context.Context, *AfterTurnKernelRequest) (*AfterTurnKernelResponse, error)
	AssembleContextInternal(context.Context, *AssembleContextInternalRequest) (*AssembleContextInternalResponse, error)
	// Ranking
	RankCandidates(context.Context, *RankCandidatesRequest) (*RankCandidatesResponse, error)
	// Cognitive
	CognitiveMetrics(context.Context, *CognitiveMetricsRequest) (*CognitiveMetricsResponse, error)
	mustEmbedUnimplementedLibravDBServer()
}

// UnimplementedLibravDBServer must be embedded to have forward compatible implementations.
type UnimplementedLibravDBServer struct {
}

func (UnimplementedLibravDBServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLibravDBServer) Status(context.Context, *MemoryStatusRequest) (*MemoryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedLibravDBServer) DaemonStatus(context.Context, *DaemonStatusRequest) (*DaemonStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DaemonStatus not implemented")
}
func (UnimplementedLibravDBServer) EvictTenant(context.Context, *EvictTenantRequest) (*EvictTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvictTenant not implemented")
}
func (UnimplementedLibravDBServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedLibravDBServer) SessionLifecycleHint(context.Context, *SessionLifecycleHintRequest) (*SessionLifecycleHintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionLifecycleHint not implemented")
}
func (UnimplementedLibravDBServer) ListLifecycleJournal(context.Context, *ListLifecycleJournalRequest) (*ListLifecycleJournalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLifecycleJournal not implemented")
}
func (UnimplementedLibravDBServer) EnsureCollections(context.Context, *EnsureCollectionsRequest) (*EnsureCollectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureCollections not implemented")
}
func (UnimplementedLibravDBServer) IngestMarkdownDocument(context.Context, *IngestMarkdownDocumentRequest) (*IngestMarkdownDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestMarkdownDocument not implemented")
}
func (UnimplementedLibravDBServer) PromoteDreamEntries(context.Context, *PromoteDreamEntriesRequest) (*DreamPromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoteDreamEntries not implemented")
}
func (UnimplementedLibravDBServer) ReindexAuthoredDocument(context.Context, *ReindexAuthoredDocumentRequest) (*ReindexAuthoredDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReindexAuthoredDocument not implemented")
}
func (UnimplementedLibravDBServer) DeleteAuthoredDocument(context.Context, *DeleteAuthoredDocumentRequest) (*DeleteAuthoredDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAuthoredDocument not implemented")
}
func (UnimplementedLibravDBServer) MarkMemorySuperseded(context.Context, *MarkMemorySupersededRequest) (*MarkMemorySupersededResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkMemorySuperseded not implemented")
}
func (UnimplementedLibravDBServer) InsertText(context.Context, *InsertTextRequest) (*InsertTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertText not implemented")
}
func (UnimplementedLibravDBServer) InsertSessionTurn(context.Context, *InsertSessionTurnRequest) (*InsertSessionTurnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertSessionTurn not implemented")
}
func (UnimplementedLibravDBServer) GatingScalar(context.Context, *GatingScalarRequest) (*GatingScalarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatingScalar not implemented")
}
func (UnimplementedLibravDBServer) SearchText(context.Context, *SearchTextRequest) (*SearchTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchText not implemented")
}
func (UnimplementedLibravDBServer) SearchTextCollections(context.Context, *SearchTextCollectionsRequest) (*SearchTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTextCollections not implemented")
}
func (UnimplementedLibravDBServer) BumpAccessCounts(context.Context, *BumpAccessCountsRequest) (*BumpAccessCountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BumpAccessCounts not implemented")
}
func (UnimplementedLibravDBServer) ListCollection(context.Context, *ListCollectionRequest) (*ListCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCollection not implemented")
}
func (UnimplementedLibravDBServer) ListByMeta(context.Context, *ListByMetaRequest) (*ListByMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByMeta not implemented")
}
func (UnimplementedLibravDBServer) ExportMemory(context.Context, *ExportMemoryRequest) (*ExportMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportMemory not implemented")
}
func (UnimplementedLibravDBServer) FlushNamespace(context.Context, *FlushNamespaceRequest) (*FlushNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlushNamespace not implemented")
}
func (UnimplementedLibravDBServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedLibravDBServer) DeleteBatch(context.Context, *DeleteBatchRequest) (*DeleteBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBatch not implemented")
}
func (UnimplementedLibravDBServer) CompactSession(context.Context, *CompactSessionRequest) (*CompactSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompactSession not implemented")
}
func (UnimplementedLibravDBServer) SummarizeMessages(context.Context, *SummarizeMessagesRequest) (*SummarizeMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SummarizeMessages not implemented")
}
func (UnimplementedLibravDBServer) ExpandSummary(context.Context, *ExpandSummaryRequest) (*ExpandSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpandSummary not implemented")
}
func (UnimplementedLibravDBServer) QueryRawSession(context.Context, *QueryRawSessionRequest) (*QueryRawSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRawSession not implemented")
}
func (UnimplementedLibravDBServer) RebuildIndex(context.Context, *RebuildIndexRequest) (*RebuildIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildIndex not implemented")
}
func (UnimplementedLibravDBServer) BootstrapSessionKernel(context.Context, *BootstrapSessionKernelRequest) (*BootstrapSessionKernelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BootstrapSessionKernel not implemented")
}
func (UnimplementedLibravDBServer) IngestMessageKernel(context.Context, *IngestMessageKernelRequest) (*IngestMessageKernelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestMessageKernel not implemented")
}
func (UnimplementedLibravDBServer) BeforeTurnKernel(context.Context, *BeforeTurnKernelRequest) (*BeforeTurnKernelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeforeTurnKernel not implemented")
}
func (UnimplementedLibravDBServer) AfterTurnKernel(context.Context, *AfterTurnKernelRequest) (*AfterTurnKernelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AfterTurnKernel not implemented")
}
func (UnimplementedLibravDBServer) AssembleContextInternal(context.Context, *AssembleContextInternalRequest) (*AssembleContextInternalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssembleContextInternal not implemented")
}
func (UnimplementedLibravDBServer) RankCandidates(context.Context, *RankCandidatesRequest) (*RankCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RankCandidates not implemented")
}
func (UnimplementedLibravDBServer) CognitiveMetrics(context.Context, *CognitiveMetricsRequest) (*CognitiveMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CognitiveMetrics not implemented")
}
func (UnimplementedLibravDBServer) mustEmbedUnimplementedLibravDBServer() {}

// UnsafeLibravDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LibravDBServer will
// result in compilation errors.
type UnsafeLibravDBServer interface {
	mustEmbedUnimplementedLibravDBServer()
}

func RegisterLibravDBServer(s grpc.ServiceRegistrar, srv LibravDBServer) {
	s.RegisterService(&LibravDB_ServiceDesc, srv)
}

func _LibravDB_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).Status(ctx, req.(*MemoryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_DaemonStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).DaemonStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_DaemonStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).DaemonStatus(ctx, req.(*DaemonStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_EvictTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).EvictTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_EvictTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).EvictTenant(ctx, req.(*EvictTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_SessionLifecycleHint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionLifecycleHintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).SessionLifecycleHint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_SessionLifecycleHint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).SessionLifecycleHint(ctx, req.(*SessionLifecycleHintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_ListLifecycleJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLifecycleJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).ListLifecycleJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_ListLifecycleJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).ListLifecycleJournal(ctx, req.(*ListLifecycleJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_EnsureCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).EnsureCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_EnsureCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).EnsureCollections(ctx, req.(*EnsureCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_IngestMarkdownDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestMarkdownDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).IngestMarkdownDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_IngestMarkdownDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).IngestMarkdownDocument(ctx, req.(*IngestMarkdownDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_PromoteDreamEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteDreamEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).PromoteDreamEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_PromoteDreamEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).PromoteDreamEntries(ctx, req.(*PromoteDreamEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_ReindexAuthoredDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexAuthoredDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).ReindexAuthoredDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_ReindexAuthoredDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).ReindexAuthoredDocument(ctx, req.(*ReindexAuthoredDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_DeleteAuthoredDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAuthoredDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).DeleteAuthoredDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_DeleteAuthoredDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).DeleteAuthoredDocument(ctx, req.(*DeleteAuthoredDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_MarkMemorySuperseded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkMemorySupersededRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).MarkMemorySuperseded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_MarkMemorySuperseded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).MarkMemorySuperseded(ctx, req.(*MarkMemorySupersededRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_InsertText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).InsertText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_InsertText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).InsertText(ctx, req.(*InsertTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_InsertSessionTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertSessionTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).InsertSessionTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_InsertSessionTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).InsertSessionTurn(ctx, req.(*InsertSessionTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_GatingScalar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatingScalarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).GatingScalar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_GatingScalar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).GatingScalar(ctx, req.(*GatingScalarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_SearchText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).SearchText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_SearchText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).SearchText(ctx, req.(*SearchTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_SearchTextCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTextCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).SearchTextCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_SearchTextCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).SearchTextCollections(ctx, req.(*SearchTextCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_BumpAccessCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BumpAccessCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).BumpAccessCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_BumpAccessCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).BumpAccessCounts(ctx, req.(*BumpAccessCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_ListCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).ListCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_ListCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).ListCollection(ctx, req.(*ListCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_ListByMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).ListByMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_ListByMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).ListByMeta(ctx, req.(*ListByMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_ExportMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).ExportMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_ExportMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).ExportMemory(ctx, req.(*ExportMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_FlushNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).FlushNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_FlushNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).FlushNamespace(ctx, req.(*FlushNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_DeleteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).DeleteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_DeleteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).DeleteBatch(ctx, req.(*DeleteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_CompactSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).CompactSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_CompactSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).CompactSession(ctx, req.(*CompactSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_SummarizeMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).SummarizeMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_SummarizeMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).SummarizeMessages(ctx, req.(*SummarizeMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_ExpandSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).ExpandSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_ExpandSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).ExpandSummary(ctx, req.(*ExpandSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_QueryRawSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRawSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).QueryRawSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_QueryRawSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).QueryRawSession(ctx, req.(*QueryRawSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_RebuildIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).RebuildIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_RebuildIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).RebuildIndex(ctx, req.(*RebuildIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_BootstrapSessionKernel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapSessionKernelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).BootstrapSessionKernel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_BootstrapSessionKernel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).BootstrapSessionKernel(ctx, req.(*BootstrapSessionKernelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_IngestMessageKernel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestMessageKernelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).IngestMessageKernel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_IngestMessageKernel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).IngestMessageKernel(ctx, req.(*IngestMessageKernelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_BeforeTurnKernel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeTurnKernelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).BeforeTurnKernel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_BeforeTurnKernel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).BeforeTurnKernel(ctx, req.(*BeforeTurnKernelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_AfterTurnKernel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfterTurnKernelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).AfterTurnKernel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_AfterTurnKernel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).AfterTurnKernel(ctx, req.(*AfterTurnKernelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_AssembleContextInternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssembleContextInternalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).AssembleContextInternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_AssembleContextInternal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).AssembleContextInternal(ctx, req.(*AssembleContextInternalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_RankCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).RankCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_RankCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).RankCandidates(ctx, req.(*RankCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibravDB_CognitiveMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CognitiveMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibravDBServer).CognitiveMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibravDB_CognitiveMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibravDBServer).CognitiveMetrics(ctx, req.(*CognitiveMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LibravDB_ServiceDesc is the grpc.ServiceDesc for LibravDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LibravDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "libravdb.ipc.v1.LibravDB",
	HandlerType: (*LibravDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _LibravDB_Health_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _LibravDB_Status_Handler,
		},
		{
			MethodName: "DaemonStatus",
			Handler:    _LibravDB_DaemonStatus_Handler,
		},
		{
			MethodName: "EvictTenant",
			Handler:    _LibravDB_EvictTenant_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _LibravDB_Flush_Handler,
		},
		{
			MethodName: "SessionLifecycleHint",
			Handler:    _LibravDB_SessionLifecycleHint_Handler,
		},
		{
			MethodName: "ListLifecycleJournal",
			Handler:    _LibravDB_ListLifecycleJournal_Handler,
		},
		{
			MethodName: "EnsureCollections",
			Handler:    _LibravDB_EnsureCollections_Handler,
		},
		{
			MethodName: "IngestMarkdownDocument",
			Handler:    _LibravDB_IngestMarkdownDocument_Handler,
		},
		{
			MethodName: "PromoteDreamEntries",
			Handler:    _LibravDB_PromoteDreamEntries_Handler,
		},
		{
			MethodName: "ReindexAuthoredDocument",
			Handler:    _LibravDB_ReindexAuthoredDocument_Handler,
		},
		{
			MethodName: "DeleteAuthoredDocument",
			Handler:    _LibravDB_DeleteAuthoredDocument_Handler,
		},
		{
			MethodName: "MarkMemorySuperseded",
			Handler:    _LibravDB_MarkMemorySuperseded_Handler,
		},
		{
			MethodName: "InsertText",
			Handler:    _LibravDB_InsertText_Handler,
		},
		{
			MethodName: "InsertSessionTurn",
			Handler:    _LibravDB_InsertSessionTurn_Handler,
		},
		{
			MethodName: "GatingScalar",
			Handler:    _LibravDB_GatingScalar_Handler,
		},
		{
			MethodName: "SearchText",
			Handler:    _LibravDB_SearchText_Handler,
		},
		{
			MethodName: "SearchTextCollections",
			Handler:    _LibravDB_SearchTextCollections_Handler,
		},
		{
			MethodName: "BumpAccessCounts",
			Handler:    _LibravDB_BumpAccessCounts_Handler,
		},
		{
			MethodName: "ListCollection",
			Handler:    _LibravDB_ListCollection_Handler,
		},
		{
			MethodName: "ListByMeta",
			Handler:    _LibravDB_ListByMeta_Handler,
		},
		{
			MethodName: "ExportMemory",
			Handler:    _LibravDB_ExportMemory_Handler,
		},
		{
			MethodName: "FlushNamespace",
			Handler:    _LibravDB_FlushNamespace_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _LibravDB_Delete_Handler,
		},
		{
			MethodName: "DeleteBatch",
			Handler:    _LibravDB_DeleteBatch_Handler,
		},
		{
			MethodName: "CompactSession",
			Handler:    _LibravDB_CompactSession_Handler,
		},
		{
			MethodName: "SummarizeMessages",
			Handler:    _LibravDB_SummarizeMessages_Handler,
		},
		{
			MethodName: "ExpandSummary",
			Handler:    _LibravDB_ExpandSummary_Handler,
		},
		{
			MethodName: "QueryRawSession",
			Handler:    _LibravDB_QueryRawSession_Handler,
		},
		{
			MethodName: "RebuildIndex",
			Handler:    _LibravDB_RebuildIndex_Handler,
		},
		{
			MethodName: "BootstrapSessionKernel",
			Handler:    _LibravDB_BootstrapSessionKernel_Handler,
		},
		{
			MethodName: "IngestMessageKernel",
			Handler:    _LibravDB_IngestMessageKernel_Handler,
		},
		{
			MethodName: "BeforeTurnKernel",
			Handler:    _LibravDB_BeforeTurnKernel_Handler,
		},
		{
			MethodName: "AfterTurnKernel",
			Handler:    _LibravDB_AfterTurnKernel_Handler,
		},
		{
			MethodName: "AssembleContextInternal",
			Handler:    _LibravDB_AssembleContextInternal_Handler,
		},
		{
			MethodName: "RankCandidates",
			Handler:    _LibravDB_RankCandidates_Handler,
		},
		{
			MethodName: "CognitiveMetrics",
			Handler:    _LibravDB_CognitiveMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "libravdb/ipc/v1/rpc.proto",
}
